/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/chat`; params?: Router.UnknownInputParams; } | { pathname: `/guidance`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/BannerAdComponent`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/NativeAdLoading`; params?: Router.UnknownInputParams; } | { pathname: `/../backend/src/index`; params?: Router.UnknownInputParams; } | { pathname: `/../backend/src/routes/guidance`; params?: Router.UnknownInputParams; } | { pathname: `/../backend/src/routes/explain`; params?: Router.UnknownInputParams; } | { pathname: `/../backend/src/routes/chat`; params?: Router.UnknownInputParams; } | { pathname: `/../backend/src/services/openrouter`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/bookmarks` | `/bookmarks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chats` | `/chats`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/new` | `/new`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/chat`; params?: Router.UnknownOutputParams; } | { pathname: `/guidance`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/components/BannerAdComponent`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/components/NativeAdLoading`; params?: Router.UnknownOutputParams; } | { pathname: `/../backend/src/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../backend/src/routes/guidance`; params?: Router.UnknownOutputParams; } | { pathname: `/../backend/src/routes/explain`; params?: Router.UnknownOutputParams; } | { pathname: `/../backend/src/routes/chat`; params?: Router.UnknownOutputParams; } | { pathname: `/../backend/src/services/openrouter`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/bookmarks` | `/bookmarks`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/chats` | `/chats`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/new` | `/new`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/chat${`?${string}` | `#${string}` | ''}` | `/guidance${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/../src/components/BannerAdComponent${`?${string}` | `#${string}` | ''}` | `/../src/components/NativeAdLoading${`?${string}` | `#${string}` | ''}` | `/../backend/src/index${`?${string}` | `#${string}` | ''}` | `/../backend/src/routes/guidance${`?${string}` | `#${string}` | ''}` | `/../backend/src/routes/explain${`?${string}` | `#${string}` | ''}` | `/../backend/src/routes/chat${`?${string}` | `#${string}` | ''}` | `/../backend/src/services/openrouter${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/bookmarks${`?${string}` | `#${string}` | ''}` | `/bookmarks${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/chats${`?${string}` | `#${string}` | ''}` | `/chats${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/new${`?${string}` | `#${string}` | ''}` | `/new${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/chat`; params?: Router.UnknownInputParams; } | { pathname: `/guidance`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/BannerAdComponent`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/NativeAdLoading`; params?: Router.UnknownInputParams; } | { pathname: `/../backend/src/index`; params?: Router.UnknownInputParams; } | { pathname: `/../backend/src/routes/guidance`; params?: Router.UnknownInputParams; } | { pathname: `/../backend/src/routes/explain`; params?: Router.UnknownInputParams; } | { pathname: `/../backend/src/routes/chat`; params?: Router.UnknownInputParams; } | { pathname: `/../backend/src/services/openrouter`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/bookmarks` | `/bookmarks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chats` | `/chats`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/new` | `/new`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; };
    }
  }
}
